sudo: false
language: node_js
node_js:
  - 'node'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install -g codecov
script:
  - npm run test && codecov
